# pylint: disable=W0613, C0114, C0115, C0116, C0301

import collections.abc
import typing

import discord
from discord.ext import commands

import patrick

class NoRelayException(Exception):
    ...


class BaseConversionError(ValueError):
    """
    Error to be used to forward custom exceptions from within :func:`baseconvert`.
    """


class RelayMember(discord.Member):
    """
    Subclass of discord.Member to signify that the member is a relay member.
    """

    @classmethod
    def _roles_from_name(cls, bot: patrick.Patrick, role_name: str) -> list[int]: ...
    @classmethod
    def from_member(cls, bot: patrick.Patrick, member: discord.User | discord.Member, nick: str, role_name: str) -> RelayMember: ...


def mention(user_id: int) -> str: ...
def user_log_repr(user: discord.User | discord.Member) -> str: ...
def escape_nickname(name: str) -> str: ...
def url_wrap(url: str, **params: str) -> str: ...
def return_or_truncate(text: str, max_length: int) -> str: ...
def reformat_relay_chat(bot: patrick.Patrick, message: discord.Message, role_name: str, author_name: str, content: str) -> discord.Message: ...
def get_raw_prefixes(bot: patrick.Patrick) -> list[str]: ...
def get_message_command_names(bot: patrick.Patrick, message: str) -> collections.abc.Generator[str]: ...
async def process_custom_command(bot: patrick.Patrick, message: discord.Message) -> bool: ...
def load_automod_regexes(bot: patrick.Patrick) -> None: ...
def find_automod_matches(bot: patrick.Patrick, message: str) -> list[str]: ...
def is_staff[T]() -> collections.abc.Callable[[T], T]: ...
def app_is_staff[T]() -> collections.abc.Callable[[T], T]: ...
def is_admin[T]() -> collections.abc.Callable[[T], T]: ...
def app_is_admin[T]() -> collections.abc.Callable[[T], T]: ...
def is_discord_member[T]() -> collections.abc.Callable[[T], T]: ...
def split_list[S: collections.abc.Sequence[typing.Any]](a: S, n: int) -> list[S]: ...
def baseconvert(number: str, base_from: int, base_to: int) -> str: ...
async def create_deletion_embed(staff: discord.Member | discord.User, reason: str, message: discord.Message) -> tuple[discord.Embed, list[discord.File]]: ...
async def create_automod_embed(message: str, matches: list[str]) -> discord.Embed: ...
def get_all_command_names(bot: commands.Bot) -> list[str]: ...
async def reply(ctx: commands.Context[patrick.Patrick], message: str | None = None, is_reply: bool = False, is_silent: bool = False, **kwargs: typing.Any) -> discord.Message: ...
